[package]
name = "aether_lib"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "aether_lib"
path = "src/lib.rs"

[dependencies]
crossbeam = "0.8.1"
