name: Deploy Docs

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  rust-doc:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Docs
      run: cargo doc --no-deps --release

    - name: Deploy Docs
      uses: peaceiris/actions-gh-pages@v3.7.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./target/doc
        force_orphan: true
