name: Clippy Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, staged ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Clippy
      run: cargo clippy
